@startuml

left to right direction
skinparam defaultFontSize 40
skinparam defaultFontName "Segoe UI"

skinparam defaultFontStyle bold
skinparam classFontStyle bold
skinparam componentFontStyle bold
skinparam noteFontStyle bold

skinparam package {
  BackgroundColor #DDF
  BorderColor #00F
  FontColor Black
}

title TextNexus Paketų diagrama

skinparam linetype ortho
skinparam PackagePadding 2000
skinparam ArrowColor Black
skinparam ArrowFontColor Black
skinparam ArrowFontSize 14
skinparam ArrowFontStyle bold
skinparam ArrowThickness 3
skinparam RankSep 100
skinparam NodeSep 200
skinparam ArrowColor<<use>> Green
skinparam ArrowColor<<import>> Blue
skinparam ArrowColor<<merge>> DarkOrange

' === PACKAGE STRUCTURE ===

package "app_logic" {
    [app.py] as App
    [api.py] as API
    [access_controller.py] as AccessController
    [settings.py] as Settings
}

package "llm_engine" {
    [models.py] as LLMEngine
}

package "templates" {
  [HTML templates] as TemplatesComponent
}

package "database" {
    [database.py] as DB
    [textnexus.db]
    [identifier.sqlite]
}

[torch]
[openai]

skinparam component {
  BackgroundColor<<invisible>> white
  BorderColor<<invisible>> white
}

' === RELATIONSHIPS ===
"app_logic" ..> TemplatesComponent : <<use>>
"app_logic" ..> "llm_engine" : <<use>>
"app_logic" ..> "database" : <<use>>
"llm_engine" ..> "database" : <<use>>
"llm_engine" --> torch : <<import>>
"llm_engine" --> openai : <<import>>

@enduml